export const PROJECT_ADD_REQUEST = "PROJECT_ADD_REQUEST";
export const PROJECT_ADD_SUCCESS = "PROJECT_ADD_SUCCESS";
export const PROJECT_ADD_FAIL = "PROJECT_ADD_FAIL";

export const PROJECT_ALL_REQUEST = "PROJECT_ALL_REQUEST";
export const PROJECT_ALL_SUCCESS = "PROJECT_ALL_SUCCESS";
export const PROJECT_ALL_FAIL = "PROJECT_ALL_FAIL";

export const PROJECT_DELETE_REQUEST = "PROJECT_DELETE_REQUEST";
export const PROJECT_DELETE_SUCCESS = "PROJECT_DELETE_SUCCESS";
export const PROJECT_DELETE_FAIL = "PROJECT_DELETE_FAIL";

export const PROJECT_UPDATE_REQUEST = "PROJECT_UPDATE_REQUEST";
export const PROJECT_UPDATE_SUCCESS = "PROJECT_UPDATE_SUCCESS";
export const PROJECT_UPDATE_FAIL = "PROJECT_UPDATE_FAIL";
